/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  timestamp,
  varchar,
  numeric,
  jsonb,
  integer,
  text,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_socials_socials_links_kind = pgEnum(
  "enum_socials_socials_links_kind",
  ["facebook", "instagram", "twitter", "youtube", "github", "linkedin"],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts").default("0"),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    users_updated_at_idx: index("users_updated_at_idx").on(columns.updatedAt),
    users_created_at_idx: index("users_created_at_idx").on(columns.createdAt),
    users_email_idx: uniqueIndex("users_email_idx").on(columns.email),
  }),
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize"),
    width: numeric("width"),
    height: numeric("height"),
    focalX: numeric("focal_x"),
    focalY: numeric("focal_y"),
  },
  (columns) => ({
    media_updated_at_idx: index("media_updated_at_idx").on(columns.updatedAt),
    media_created_at_idx: index("media_created_at_idx").on(columns.createdAt),
    media_filename_idx: uniqueIndex("media_filename_idx").on(columns.filename),
  }),
);

export const notes = pgTable(
  "notes",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    content: jsonb("content"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    notes_updated_at_idx: index("notes_updated_at_idx").on(columns.updatedAt),
    notes_created_at_idx: index("notes_created_at_idx").on(columns.createdAt),
  }),
);

export const experiances = pgTable(
  "experiances",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    content: jsonb("content"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    experiances_updated_at_idx: index("experiances_updated_at_idx").on(
      columns.updatedAt,
    ),
    experiances_created_at_idx: index("experiances_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const skills = pgTable(
  "skills",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    skills_updated_at_idx: index("skills_updated_at_idx").on(columns.updatedAt),
    skills_created_at_idx: index("skills_created_at_idx").on(columns.createdAt),
  }),
);

export const educations = pgTable(
  "educations",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    educations_updated_at_idx: index("educations_updated_at_idx").on(
      columns.updatedAt,
    ),
    educations_created_at_idx: index("educations_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const projects = pgTable(
  "projects",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    projects_updated_at_idx: index("projects_updated_at_idx").on(
      columns.updatedAt,
    ),
    projects_created_at_idx: index("projects_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const blogs = pgTable(
  "blogs",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    content: jsonb("content"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    blogs_updated_at_idx: index("blogs_updated_at_idx").on(columns.updatedAt),
    blogs_created_at_idx: index("blogs_created_at_idx").on(columns.createdAt),
  }),
);

export const pages_blocks_blog = pgTable(
  "pages_blocks_blog",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("pages_blocks_blog_order_idx").on(columns._order),
    _parentIDIdx: index("pages_blocks_blog_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("pages_blocks_blog_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_blog_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const pages_blocks_contact = pgTable(
  "pages_blocks_contact",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("pages_blocks_contact_order_idx").on(columns._order),
    _parentIDIdx: index("pages_blocks_contact_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("pages_blocks_contact_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_contact_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const pages_blocks_education = pgTable(
  "pages_blocks_education",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("pages_blocks_education_order_idx").on(columns._order),
    _parentIDIdx: index("pages_blocks_education_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("pages_blocks_education_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_education_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const pages_blocks_me = pgTable(
  "pages_blocks_me",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    nameOnResume: varchar("name_on_resume"),
    aboutMe: jsonb("about_me"),
    profile: integer("profile_id").references(() => media.id, {
      onDelete: "set null",
    }),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("pages_blocks_me_order_idx").on(columns._order),
    _parentIDIdx: index("pages_blocks_me_parent_id_idx").on(columns._parentID),
    _pathIdx: index("pages_blocks_me_path_idx").on(columns._path),
    pages_blocks_me_profile_idx: index("pages_blocks_me_profile_idx").on(
      columns.profile,
    ),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_me_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const pages_blocks_skill = pgTable(
  "pages_blocks_skill",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("pages_blocks_skill_order_idx").on(columns._order),
    _parentIDIdx: index("pages_blocks_skill_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("pages_blocks_skill_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_skill_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    pages_updated_at_idx: index("pages_updated_at_idx").on(columns.updatedAt),
    pages_created_at_idx: index("pages_created_at_idx").on(columns.createdAt),
  }),
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index(
      "payload_locked_documents_global_slug_idx",
    ).on(columns.globalSlug),
    payload_locked_documents_updated_at_idx: index(
      "payload_locked_documents_updated_at_idx",
    ).on(columns.updatedAt),
    payload_locked_documents_created_at_idx: index(
      "payload_locked_documents_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    notesID: integer("notes_id"),
    experiancesID: integer("experiances_id"),
    skillsID: integer("skills_id"),
    educationsID: integer("educations_id"),
    projectsID: integer("projects_id"),
    blogsID: integer("blogs_id"),
    pagesID: integer("pages_id"),
  },
  (columns) => ({
    order: index("payload_locked_documents_rels_order_idx").on(columns.order),
    parentIdx: index("payload_locked_documents_rels_parent_idx").on(
      columns.parent,
    ),
    pathIdx: index("payload_locked_documents_rels_path_idx").on(columns.path),
    payload_locked_documents_rels_users_id_idx: index(
      "payload_locked_documents_rels_users_id_idx",
    ).on(columns.usersID),
    payload_locked_documents_rels_media_id_idx: index(
      "payload_locked_documents_rels_media_id_idx",
    ).on(columns.mediaID),
    payload_locked_documents_rels_notes_id_idx: index(
      "payload_locked_documents_rels_notes_id_idx",
    ).on(columns.notesID),
    payload_locked_documents_rels_experiances_id_idx: index(
      "payload_locked_documents_rels_experiances_id_idx",
    ).on(columns.experiancesID),
    payload_locked_documents_rels_skills_id_idx: index(
      "payload_locked_documents_rels_skills_id_idx",
    ).on(columns.skillsID),
    payload_locked_documents_rels_educations_id_idx: index(
      "payload_locked_documents_rels_educations_id_idx",
    ).on(columns.educationsID),
    payload_locked_documents_rels_projects_id_idx: index(
      "payload_locked_documents_rels_projects_id_idx",
    ).on(columns.projectsID),
    payload_locked_documents_rels_blogs_id_idx: index(
      "payload_locked_documents_rels_blogs_id_idx",
    ).on(columns.blogsID),
    payload_locked_documents_rels_pages_id_idx: index(
      "payload_locked_documents_rels_pages_id_idx",
    ).on(columns.pagesID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    mediaIdFk: foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    notesIdFk: foreignKey({
      columns: [columns["notesID"]],
      foreignColumns: [notes.id],
      name: "payload_locked_documents_rels_notes_fk",
    }).onDelete("cascade"),
    experiancesIdFk: foreignKey({
      columns: [columns["experiancesID"]],
      foreignColumns: [experiances.id],
      name: "payload_locked_documents_rels_experiances_fk",
    }).onDelete("cascade"),
    skillsIdFk: foreignKey({
      columns: [columns["skillsID"]],
      foreignColumns: [skills.id],
      name: "payload_locked_documents_rels_skills_fk",
    }).onDelete("cascade"),
    educationsIdFk: foreignKey({
      columns: [columns["educationsID"]],
      foreignColumns: [educations.id],
      name: "payload_locked_documents_rels_educations_fk",
    }).onDelete("cascade"),
    projectsIdFk: foreignKey({
      columns: [columns["projectsID"]],
      foreignColumns: [projects.id],
      name: "payload_locked_documents_rels_projects_fk",
    }).onDelete("cascade"),
    blogsIdFk: foreignKey({
      columns: [columns["blogsID"]],
      foreignColumns: [blogs.id],
      name: "payload_locked_documents_rels_blogs_fk",
    }).onDelete("cascade"),
    pagesIdFk: foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index("payload_preferences_key_idx").on(
      columns.key,
    ),
    payload_preferences_updated_at_idx: index(
      "payload_preferences_updated_at_idx",
    ).on(columns.updatedAt),
    payload_preferences_created_at_idx: index(
      "payload_preferences_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => ({
    order: index("payload_preferences_rels_order_idx").on(columns.order),
    parentIdx: index("payload_preferences_rels_parent_idx").on(columns.parent),
    pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
    payload_preferences_rels_users_id_idx: index(
      "payload_preferences_rels_users_id_idx",
    ).on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index(
      "payload_migrations_updated_at_idx",
    ).on(columns.updatedAt),
    payload_migrations_created_at_idx: index(
      "payload_migrations_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const menu_menu = pgTable(
  "menu_menu",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    page: integer("page_id").references(() => pages.id, {
      onDelete: "set null",
    }),
  },
  (columns) => ({
    _orderIdx: index("menu_menu_order_idx").on(columns._order),
    _parentIDIdx: index("menu_menu_parent_id_idx").on(columns._parentID),
    menu_menu_page_idx: index("menu_menu_page_idx").on(columns.page),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [menu.id],
      name: "menu_menu_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const menu = pgTable("menu", {
  id: serial("id").primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const socials_socials_links = pgTable(
  "socials_socials_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    kind: enum_socials_socials_links_kind("kind"),
    link: varchar("link"),
  },
  (columns) => ({
    _orderIdx: index("socials_socials_links_order_idx").on(columns._order),
    _parentIDIdx: index("socials_socials_links_parent_id_idx").on(
      columns._parentID,
    ),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [socials.id],
      name: "socials_socials_links_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const socials = pgTable("socials", {
  id: serial("id").primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_users = relations(users, () => ({}));
export const relations_media = relations(media, () => ({}));
export const relations_notes = relations(notes, () => ({}));
export const relations_experiances = relations(experiances, () => ({}));
export const relations_skills = relations(skills, () => ({}));
export const relations_educations = relations(educations, () => ({}));
export const relations_projects = relations(projects, () => ({}));
export const relations_blogs = relations(blogs, () => ({}));
export const relations_pages_blocks_blog = relations(
  pages_blocks_blog,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_blog._parentID],
      references: [pages.id],
      relationName: "_blocks_blog",
    }),
  }),
);
export const relations_pages_blocks_contact = relations(
  pages_blocks_contact,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_contact._parentID],
      references: [pages.id],
      relationName: "_blocks_contact",
    }),
  }),
);
export const relations_pages_blocks_education = relations(
  pages_blocks_education,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_education._parentID],
      references: [pages.id],
      relationName: "_blocks_education",
    }),
  }),
);
export const relations_pages_blocks_me = relations(
  pages_blocks_me,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_me._parentID],
      references: [pages.id],
      relationName: "_blocks_me",
    }),
    profile: one(media, {
      fields: [pages_blocks_me.profile],
      references: [media.id],
      relationName: "profile",
    }),
  }),
);
export const relations_pages_blocks_skill = relations(
  pages_blocks_skill,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_skill._parentID],
      references: [pages.id],
      relationName: "_blocks_skill",
    }),
  }),
);
export const relations_pages = relations(pages, ({ many }) => ({
  _blocks_blog: many(pages_blocks_blog, {
    relationName: "_blocks_blog",
  }),
  _blocks_contact: many(pages_blocks_contact, {
    relationName: "_blocks_contact",
  }),
  _blocks_education: many(pages_blocks_education, {
    relationName: "_blocks_education",
  }),
  _blocks_me: many(pages_blocks_me, {
    relationName: "_blocks_me",
  }),
  _blocks_skill: many(pages_blocks_skill, {
    relationName: "_blocks_skill",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    notesID: one(notes, {
      fields: [payload_locked_documents_rels.notesID],
      references: [notes.id],
      relationName: "notes",
    }),
    experiancesID: one(experiances, {
      fields: [payload_locked_documents_rels.experiancesID],
      references: [experiances.id],
      relationName: "experiances",
    }),
    skillsID: one(skills, {
      fields: [payload_locked_documents_rels.skillsID],
      references: [skills.id],
      relationName: "skills",
    }),
    educationsID: one(educations, {
      fields: [payload_locked_documents_rels.educationsID],
      references: [educations.id],
      relationName: "educations",
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: "projects",
    }),
    blogsID: one(blogs, {
      fields: [payload_locked_documents_rels.blogsID],
      references: [blogs.id],
      relationName: "blogs",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_menu_menu = relations(menu_menu, ({ one }) => ({
  _parentID: one(menu, {
    fields: [menu_menu._parentID],
    references: [menu.id],
    relationName: "menu",
  }),
  page: one(pages, {
    fields: [menu_menu.page],
    references: [pages.id],
    relationName: "page",
  }),
}));
export const relations_menu = relations(menu, ({ many }) => ({
  menu: many(menu_menu, {
    relationName: "menu",
  }),
}));
export const relations_socials_socials_links = relations(
  socials_socials_links,
  ({ one }) => ({
    _parentID: one(socials, {
      fields: [socials_socials_links._parentID],
      references: [socials.id],
      relationName: "socialsLinks",
    }),
  }),
);
export const relations_socials = relations(socials, ({ many }) => ({
  socialsLinks: many(socials_socials_links, {
    relationName: "socialsLinks",
  }),
}));

type DatabaseSchema = {
  enum_socials_socials_links_kind: typeof enum_socials_socials_links_kind;
  users: typeof users;
  media: typeof media;
  notes: typeof notes;
  experiances: typeof experiances;
  skills: typeof skills;
  educations: typeof educations;
  projects: typeof projects;
  blogs: typeof blogs;
  pages_blocks_blog: typeof pages_blocks_blog;
  pages_blocks_contact: typeof pages_blocks_contact;
  pages_blocks_education: typeof pages_blocks_education;
  pages_blocks_me: typeof pages_blocks_me;
  pages_blocks_skill: typeof pages_blocks_skill;
  pages: typeof pages;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  menu_menu: typeof menu_menu;
  menu: typeof menu;
  socials_socials_links: typeof socials_socials_links;
  socials: typeof socials;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_notes: typeof relations_notes;
  relations_experiances: typeof relations_experiances;
  relations_skills: typeof relations_skills;
  relations_educations: typeof relations_educations;
  relations_projects: typeof relations_projects;
  relations_blogs: typeof relations_blogs;
  relations_pages_blocks_blog: typeof relations_pages_blocks_blog;
  relations_pages_blocks_contact: typeof relations_pages_blocks_contact;
  relations_pages_blocks_education: typeof relations_pages_blocks_education;
  relations_pages_blocks_me: typeof relations_pages_blocks_me;
  relations_pages_blocks_skill: typeof relations_pages_blocks_skill;
  relations_pages: typeof relations_pages;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_menu_menu: typeof relations_menu_menu;
  relations_menu: typeof relations_menu;
  relations_socials_socials_links: typeof relations_socials_socials_links;
  relations_socials: typeof relations_socials;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
