/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TUserRole".
 */
export type TUserRole = ('super-admin' | 'user')[] | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TUserTenants".
 */
export type TUserTenants =
  | {
      tenant: number | Tenant;
      roles: ('tenant-admin' | 'tenant-viewer')[];
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    hero: IHeroProps;
    contact: IContactProps;
    education: TEducationProps;
    project: IProjectProps;
    skill: ISkillProps;
    experience: IExperienceProps;
    about: IAboutProps;
    hackathon: IHackathonProps;
    research: IResearchProps;
    publication: IPublicationProps;
    license: ILicenseProps;
    certification: ICertificationProps;
    achievement: IAchievementProps;
    'github-contributions': IGithubContributionProps;
    'blogs-block': IBlogsBlockProps;
    formBlock: TFormBlockProps;
    'code-block': TCodeBlockProps;
  };
  collections: {
    users: User;
    media: Media;
    notes: Note;
    blogs: Blog;
    pages: Page;
    educations: Education;
    projects: Project;
    tenants: Tenant;
    menus: Menu;
    socials: Social;
    skills: Skill;
    hackathons: Hackathon;
    researches: Research;
    achievements: Achievement;
    certifications: Certification;
    publications: Publication;
    licenses: License;
    industries: Industry;
    experiences: Experience;
    integration: Integration;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    skills: {
      relatedExperiences: 'experiences';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    educations: EducationsSelect<false> | EducationsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    socials: SocialsSelect<false> | SocialsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    hackathons: HackathonsSelect<false> | HackathonsSelect<true>;
    researches: ResearchesSelect<false> | ResearchesSelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    licenses: LicensesSelect<false> | LicensesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    integration: IntegrationSelect<false> | IntegrationSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IHeroProps".
 */
export interface IHeroProps {
  nameOnResume?: string | null;
  headline?: string | null;
  profile?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | Tenant)[] | null;
  alt: string;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Used for domain-based tenant handling
   */
  domain?: string | null;
  /**
   * Used for url paths, example: /tenant-slug/page-slug
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IContactProps".
 */
export interface IContactProps {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  form?: (number | null) | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  submitButtonWidth?: number | null;
  /**
   * e.g: (Loading..., Submitting..., Subscribing...) etc
   */
  submitButtonLoadingText?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  content: {
    /**
     * If you want to show your collections like: Blogs, Notes, Publications, Projects etc then you have to change Page Mode into collection.
     */
    pageMode: {
      mode: 'layout' | 'collection';
    };
    configurations?: {
      slug?: string | null;
    };
    layout?:
      | (
          | IAboutProps
          | IContactProps
          | IHeroProps
          | ISkillProps
          | TEducationProps
          | IExperienceProps
          | IBlogsBlockProps
          | TFormBlockProps
          | IAchievementProps
          | ICertificationProps
          | IGithubContributionProps
          | IHackathonProps
          | IProjectProps
          | IPublicationProps
          | IResearchProps
          | TCodeBlockProps
          | ILicenseProps
        )[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IAboutProps".
 */
export interface IAboutProps {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISkillProps".
 */
export interface ISkillProps {
  userSkills?: (number | Skill)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'skill';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  publishedAt?: string | null;
  /**
   * If you want to show an icon of the skill instead of skill as name then you have to select an icon from icons collection. REMEMBER: If the icon is available on skill only icon will be display.
   */
  techstack?: {
    iconify?: string | null;
  };
  /**
   * Select those project in whitch you used this skill.
   */
  projects?: (number | Project)[] | null;
  relatedExperiences?: {
    docs?: (number | Experience)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  content: {
    /**
     * Provide project thumbnail.
     */
    thumbnail: number | Media;
    overview?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    detailedOverview?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    publishedAt?: string | null;
    /**
     * Provide list of skills. You used to build this project
     */
    Skills?: (number | Skill)[] | null;
    dates?: {
      to?: string | null;
      from?: string | null;
    };
    /**
     * Provide credential for testing.
     */
    credential?: {
      credential_email?: string | null;
      credential_password?: string | null;
      /**
       * If you handled your authentication with username then provide otherwize leave it.
       */
      credential_username?: string | null;
    };
    links?:
      | {
          iconify?: string | null;
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  tenant?: (number | Tenant)[] | null;
  /**
   * Job title. eg: (Frontend, Backend, DevOps, QA, ...) etc
   */
  title: string;
  /**
   * Type of employment
   */
  employmentType?: ('full-time' | 'part-time' | 'contract' | 'freelance' | 'internship') | null;
  /**
   * Choose whether this job is office-based, remote, or a mix (Hybrid).
   */
  jobType?: ('on-site' | 'remote' | 'hybrid') | null;
  company?: string | null;
  /**
   * Employment date / Joining Date
   */
  start?: string | null;
  /**
   * End date of employment. If you are skill employee of the company then leave it. We will show the present text like this (Present)
   */
  end?: string | null;
  /**
   * Company website URL
   */
  website?: string | null;
  /**
   * Location (e.g., "NY - USA", "Remote")
   */
  location?: string | null;
  /**
   * Company logo
   */
  logo?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedSkills?: (number | Skill)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TEducationProps".
 */
export interface TEducationProps {
  educations?: (number | Education)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'education';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educations".
 */
export interface Education {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  content: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    qualification?: {
      academy?: string | null;
      degree?: string | null;
    };
    dates?: {
      to?: string | null;
      from?: string | null;
    };
    image: number | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IExperienceProps".
 */
export interface IExperienceProps {
  relatedExperiences?: (number | Experience)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'experience';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IBlogsBlockProps".
 */
export interface IBlogsBlockProps {
  heading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blogs?: (number | Blog)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogs-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  content: {
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Blog short description.
     */
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    featured_image: number | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TFormBlockProps".
 */
export interface TFormBlockProps {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IAchievementProps".
 */
export interface IAchievementProps {
  heading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  achievements?: (number | Achievement)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'achievement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  content: {
    /**
     * Write description.
     */
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    dates: {
      to: string;
      from: string;
    };
    location?: string | null;
    links?:
      | {
          iconify?: string | null;
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ICertificationProps".
 */
export interface ICertificationProps {
  heading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  certifications?: (number | Certification)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'certification';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  content: {
    /**
     * Write description.
     */
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    dates: {
      to: string;
      from: string;
    };
    location?: string | null;
    links?:
      | {
          iconify?: string | null;
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IGithubContributionProps".
 */
export interface IGithubContributionProps {
  /**
   * By default we will use username from social link.
   */
  githubContributionGraphConfig: 'useAnotherUsername' | 'useSocialUsername';
  username?: string | null;
  hideMonthLabels: boolean;
  withTooltip: boolean;
  graphBlockMargin: number;
  graphBlockSize: number;
  graphFontSize: number;
  graphBlockRadius: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'github-contributions';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IHackathonProps".
 */
export interface IHackathonProps {
  heading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hackathons?: (number | Hackathon)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hackathon';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hackathons".
 */
export interface Hackathon {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  content: {
    /**
     * Write description.
     */
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    dates: {
      to: string;
      from: string;
    };
    location?: string | null;
    links?:
      | {
          iconify?: string | null;
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IProjectProps".
 */
export interface IProjectProps {
  heading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  projects?: (number | Project)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'project';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IPublicationProps".
 */
export interface IPublicationProps {
  heading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publications?: (number | Publication)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'publication';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  content: {
    /**
     * Write description.
     */
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    dates: {
      to: string;
      from: string;
    };
    location?: string | null;
    links?:
      | {
          iconify?: string | null;
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IResearchProps".
 */
export interface IResearchProps {
  heading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  researches?: (number | Research)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'research';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "researches".
 */
export interface Research {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  content: {
    /**
     * Write description.
     */
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    dates: {
      to: string;
      from: string;
    };
    location?: string | null;
    links?:
      | {
          iconify?: string | null;
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TCodeBlockProps".
 */
export interface TCodeBlockProps {
  language?: ('ts' | 'js') | null;
  code?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ILicenseProps".
 */
export interface ILicenseProps {
  heading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  licenses?: (number | License)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'license';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses".
 */
export interface License {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  content: {
    /**
     * Write description.
     */
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    dates: {
      to: string;
      from: string;
    };
    location?: string | null;
    links?:
      | {
          iconify?: string | null;
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  profile?: (number | null) | Media;
  roles?: TUserRole;
  username?: string | null;
  tenants?: TUserTenants;
  industry?: (number | null) | Industry;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  /**
   * Write description.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  tenant?: (number | Tenant)[] | null;
  title: string;
  content?: {
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  tenant?: (number | Tenant)[] | null;
  menu?:
    | {
        iconify?: string | null;
        label: string;
        page?: (number | null) | Page;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials".
 */
export interface Social {
  id: number;
  tenant?: (number | Tenant)[] | null;
  socialsLinks?:
    | {
        title: string;
        link: string;
        iconify?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration".
 */
export interface Integration {
  id: number;
  tenant?: (number | Tenant)[] | null;
  enableChatButton?: boolean | null;
  chatBubbleType?: 'tawk' | null;
  tawkPropertyId?: string | null;
  tawkWidgetId?: string | null;
  enableTawkBubble?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  tenant?: (number | Tenant)[] | null;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'educations';
        value: number | Education;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'socials';
        value: number | Social;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'hackathons';
        value: number | Hackathon;
      } | null)
    | ({
        relationTo: 'researches';
        value: number | Research;
      } | null)
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'licenses';
        value: number | License;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'integration';
        value: number | Integration;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  profile?: T;
  roles?: T;
  username?: T;
  tenants?: T | TUserTenantsSelect<T>;
  industry?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TUserTenants_select".
 */
export interface TUserTenantsSelect<T extends boolean = true> {
  tenant?: T;
  roles?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  content?:
    | T
    | {
        content?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  content?:
    | T
    | {
        content?: T;
        description?: T;
        featured_image?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  content?:
    | T
    | {
        pageMode?:
          | T
          | {
              mode?: T;
            };
        configurations?:
          | T
          | {
              slug?: T;
            };
        layout?: T | {};
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educations_select".
 */
export interface EducationsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  content?:
    | T
    | {
        description?: T;
        qualification?:
          | T
          | {
              academy?: T;
              degree?: T;
            };
        dates?:
          | T
          | {
              to?: T;
              from?: T;
            };
        image?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  content?:
    | T
    | {
        thumbnail?: T;
        overview?: T;
        detailedOverview?: T;
        publishedAt?: T;
        Skills?: T;
        dates?:
          | T
          | {
              to?: T;
              from?: T;
            };
        credential?:
          | T
          | {
              credential_email?: T;
              credential_password?: T;
              credential_username?: T;
            };
        links?:
          | T
          | {
              iconify?: T;
              label?: T;
              link?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  tenant?: T;
  menu?:
    | T
    | {
        iconify?: T;
        label?: T;
        page?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials_select".
 */
export interface SocialsSelect<T extends boolean = true> {
  tenant?: T;
  socialsLinks?:
    | T
    | {
        title?: T;
        link?: T;
        iconify?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  publishedAt?: T;
  techstack?:
    | T
    | {
        iconify?: T;
      };
  projects?: T;
  relatedExperiences?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hackathons_select".
 */
export interface HackathonsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  content?:
    | T
    | {
        description?: T;
        dates?:
          | T
          | {
              to?: T;
              from?: T;
            };
        location?: T;
        links?:
          | T
          | {
              iconify?: T;
              label?: T;
              link?: T;
              id?: T;
            };
        image?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "researches_select".
 */
export interface ResearchesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  content?:
    | T
    | {
        description?: T;
        dates?:
          | T
          | {
              to?: T;
              from?: T;
            };
        location?: T;
        links?:
          | T
          | {
              iconify?: T;
              label?: T;
              link?: T;
              id?: T;
            };
        image?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  content?:
    | T
    | {
        description?: T;
        dates?:
          | T
          | {
              to?: T;
              from?: T;
            };
        location?: T;
        links?:
          | T
          | {
              iconify?: T;
              label?: T;
              link?: T;
              id?: T;
            };
        image?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  content?:
    | T
    | {
        description?: T;
        dates?:
          | T
          | {
              to?: T;
              from?: T;
            };
        location?: T;
        links?:
          | T
          | {
              iconify?: T;
              label?: T;
              link?: T;
              id?: T;
            };
        image?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  content?:
    | T
    | {
        description?: T;
        dates?:
          | T
          | {
              to?: T;
              from?: T;
            };
        location?: T;
        links?:
          | T
          | {
              iconify?: T;
              label?: T;
              link?: T;
              id?: T;
            };
        image?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses_select".
 */
export interface LicensesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  content?:
    | T
    | {
        description?: T;
        dates?:
          | T
          | {
              to?: T;
              from?: T;
            };
        location?: T;
        links?:
          | T
          | {
              iconify?: T;
              label?: T;
              link?: T;
              id?: T;
            };
        image?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  employmentType?: T;
  jobType?: T;
  company?: T;
  start?: T;
  end?: T;
  website?: T;
  location?: T;
  logo?: T;
  description?: T;
  relatedSkills?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration_select".
 */
export interface IntegrationSelect<T extends boolean = true> {
  tenant?: T;
  enableChatButton?: T;
  chatBubbleType?: T;
  tawkPropertyId?: T;
  tawkWidgetId?: T;
  enableTawkBubble?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  submitButtonWidth?: T;
  submitButtonLoadingText?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}